/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios, { type AxiosResponse } from "axios";
import { activateContractEndpoint } from "valorant-api-types";
import { parseResponseDataFor, buildSuffix } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { AxiosRequestConfigWithData } from "~/utils/lib/axios";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";
import { type RemoteApiClient } from "~/clients/remote-api";

type ActivateContractSuffixData = { puuid: string; contractId: string };

export interface ActivateContractRequestConfig
  extends AxiosRequestConfigWithData<ActivateContractSuffixData>,
    CustomAxiosRequestConfig {}

export type ActivateContractRawResponse = z.input<
  (typeof activateContractEndpoint.responses)["200"]
>;

export type ActivateContractResponse = z.output<
  (typeof activateContractEndpoint.responses)["200"]
>;

export class ActivateContractRemoteApiEndpoint {
  /**
   * @description Activate a specific contract by ID
   */
  postActivateContract<T = ActivateContractRawResponse>(
    this: RemoteApiClient,
    config: ActivateContractRequestConfig & { parseResponseData: false },
  ): Promise<AxiosResponse<T>>;
  postActivateContract<T = ActivateContractResponse>(
    this: RemoteApiClient,
    config?: ActivateContractRequestConfig,
  ): Promise<AxiosResponse<T>>;
  postActivateContract<T = ActivateContractResponse>(
    this: RemoteApiClient,
    config: ActivateContractRequestConfig,
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "POST",
      baseURL: this.getServerUrl(activateContractEndpoint.type),
      url: buildSuffix(activateContractEndpoint.suffix, config.data),
      ...config,
      transformRequest: [
        parseResponseDataFor(activateContractEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                activateContractEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
