/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios, { type AxiosResponse } from "axios";
import { type AxiosRequestConfig } from "axios";
import { itemUpgradesEndpoint } from "valorant-api-types";
import { parseResponseDataFor } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";
import { type RemoteApiClient } from "~/clients/remote-api";

export interface ItemUpgradesRequestConfig
  extends AxiosRequestConfig,
    CustomAxiosRequestConfig {}

export type ItemUpgradesResponse = z.input<
  (typeof itemUpgradesEndpoint.responses)["200"]
>;

export type ItemUpgradesParsedResponse = z.output<
  (typeof itemUpgradesEndpoint.responses)["200"]
>;

export class ItemUpgradesRemoteApiEndpoint {
  /**
   * @description Get details for item upgrades
   */
  getItemUpgrades<T = ItemUpgradesParsedResponse>(
    this: RemoteApiClient,
    config: ItemUpgradesRequestConfig & { parseResponseData: true },
  ): Promise<AxiosResponse<T>>;
  getItemUpgrades<T = ItemUpgradesResponse>(
    this: RemoteApiClient,
    config?: ItemUpgradesRequestConfig,
  ): Promise<AxiosResponse<T>>;
  getItemUpgrades<T = ItemUpgradesResponse>(
    this: RemoteApiClient,
    config: ItemUpgradesRequestConfig = {},
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "GET",
      baseURL: this.getServerUrl(itemUpgradesEndpoint.type),
      url: itemUpgradesEndpoint.suffix,
      ...config,
      transformRequest: [
        parseResponseDataFor(itemUpgradesEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                itemUpgradesEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
