/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios from "axios";
import { storefrontEndpoint } from "valorant-api-types";
import { parseResponseDataFor, buildSuffix } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { AxiosRequestConfigWithData } from "~/utils/lib/axios";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";
import { type RemoteApiClient } from "~/clients/remote-api";

type StorefrontSuffixData = { puuid: string };

export interface StorefrontRequestConfig
  extends AxiosRequestConfigWithData<StorefrontSuffixData>,
    CustomAxiosRequestConfig {}

export type StorefrontResponse = z.infer<
  (typeof storefrontEndpoint.responses)["200"]
>;

export class StorefrontRemoteApiEndpoint {
  /**
   * @description Get the currently available items in the store
   */
  getStorefront<T = StorefrontResponse>(
    this: RemoteApiClient,
    config: StorefrontRequestConfig,
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "GET",
      baseURL: this.getServerUrl(storefrontEndpoint.type),
      url: buildSuffix(storefrontEndpoint.suffix, config.data),
      ...config,
      transformRequest: [
        parseResponseDataFor(storefrontEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                storefrontEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
