/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import { type AxiosRequestConfig } from "axios";
import { entitlementEndpoint } from "valorant-api-types";
import { type AuthApiClient } from "~/clients/auth";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";

export interface EntitlementRequestConfig
  extends AxiosRequestConfig,
    CustomAxiosRequestConfig {}

export type EntitlementResponse = z.infer<
  (typeof entitlementEndpoint.responses)["200"]
>;

export class EntitlementAuthApiEndpoint {
  /**
   * @description Get entitlement for remote requests with a token
   */
  postEntitlement<T = EntitlementResponse>(
    this: AuthApiClient,
    config: EntitlementRequestConfig = {},
  ) {
    return this.axiosInstance<T>({
      method: "POST",
      url: entitlementEndpoint.suffix,
      headers: Object.fromEntries(entitlementEndpoint.headers),
      ...config,
    });
  }
}
