/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios, { type AxiosResponse } from "axios";
import { type AxiosRequestConfig } from "axios";
import { chatHistoryEndpoint } from "@tqman/valorant-api-types";
import { parseResponseDataFor } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { type LocalApiClient } from "~/clients/local-api";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";

export interface ChatHistoryRequestConfig
  extends AxiosRequestConfig,
    CustomAxiosRequestConfig {}

export type ChatHistoryResponse = z.input<
  (typeof chatHistoryEndpoint.responses)["200"]
>;

export type ChatHistoryParsedResponse = z.output<
  (typeof chatHistoryEndpoint.responses)["200"]
>;

export class ChatHistoryLocalApiEndpoint {
  /**
   * @description Get chat history for all conversations or a specific conversation if the cid is provided
   */
  getChatHistory<T = ChatHistoryParsedResponse>(
    this: LocalApiClient,
    config: ChatHistoryRequestConfig & { parseResponseData: true },
  ): Promise<AxiosResponse<T>>;
  getChatHistory<T = ChatHistoryResponse>(
    this: LocalApiClient,
    config?: ChatHistoryRequestConfig,
  ): Promise<AxiosResponse<T>>;
  getChatHistory<T = ChatHistoryResponse>(
    this: LocalApiClient,
    config: ChatHistoryRequestConfig = {},
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "GET",
      url: chatHistoryEndpoint.suffix,
      ...config,
      transformRequest: [
        parseResponseDataFor(chatHistoryEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                chatHistoryEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
