/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios, { type AxiosResponse } from "axios";
import { type AxiosRequestConfig } from "axios";
import { clientRegionEndpoint } from "@tqman/valorant-api-types";
import { parseResponseDataFor } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { type LocalApiClient } from "~/clients/local-api";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";

export interface ClientRegionRequestConfig
  extends AxiosRequestConfig,
    CustomAxiosRequestConfig {}

export type ClientRegionResponse = z.input<
  (typeof clientRegionEndpoint.responses)["200"]
>;

export type ClientRegionParsedResponse = z.output<
  (typeof clientRegionEndpoint.responses)["200"]
>;

export class ClientRegionLocalApiEndpoint {
  /**
   * @description Gets info about the region and locale from the Riot client
   */
  getClientRegion<T = ClientRegionParsedResponse>(
    this: LocalApiClient,
    config: ClientRegionRequestConfig & { parseResponseData: true },
  ): Promise<AxiosResponse<T>>;
  getClientRegion<T = ClientRegionResponse>(
    this: LocalApiClient,
    config?: ClientRegionRequestConfig,
  ): Promise<AxiosResponse<T>>;
  getClientRegion<T = ClientRegionResponse>(
    this: LocalApiClient,
    config: ClientRegionRequestConfig = {},
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "GET",
      url: clientRegionEndpoint.suffix,
      ...config,
      transformRequest: [
        parseResponseDataFor(clientRegionEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                clientRegionEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
