/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { LocalHelpLocalApiEndpoint } from "./local-help";
import { SessionsLocalApiEndpoint } from "./sessions";
import { RsoUserInfoLocalApiEndpoint } from "./rso-user-info";
import { ClientRegionLocalApiEndpoint } from "./client-region";
import { AccountAliasLocalApiEndpoint } from "./account-alias";
import { EntitlementsTokenLocalApiEndpoint } from "./entitlements-token";
import { ChatSessionLocalApiEndpoint } from "./chat-session";
import { FriendsLocalApiEndpoint } from "./friends";
import { SendFriendRequestLocalApiEndpoint } from "./send-friend-request";
import { RemoveFriendRequestLocalApiEndpoint } from "./remove-friend-request";
import { PresenceLocalApiEndpoint } from "./presence";
import { SettingsLocalApiEndpoint } from "./settings";
import { FriendRequestsLocalApiEndpoint } from "./friend-requests";
import { LocalSwaggerDocsLocalApiEndpoint } from "./local-swagger-docs";
import { PartyChatInfoLocalApiEndpoint } from "./party-chat-info";
import { PreGameChatInfoLocalApiEndpoint } from "./pre-game-chat-info";
import { CurrentGameChatInfoLocalApiEndpoint } from "./current-game-chat-info";
import { AllChatInfoLocalApiEndpoint } from "./all-chat-info";
import { ChatParticipantsLocalApiEndpoint } from "./chat-participants";
import { SendChatLocalApiEndpoint } from "./send-chat";
import { ChatHistoryLocalApiEndpoint } from "./chat-history";

import { applyMixins } from "~/utils/classes";

export class LocalApiEndpoints {}

applyMixins(LocalApiEndpoints, [
  LocalHelpLocalApiEndpoint,
  SessionsLocalApiEndpoint,
  RsoUserInfoLocalApiEndpoint,
  ClientRegionLocalApiEndpoint,
  AccountAliasLocalApiEndpoint,
  EntitlementsTokenLocalApiEndpoint,
  ChatSessionLocalApiEndpoint,
  FriendsLocalApiEndpoint,
  SendFriendRequestLocalApiEndpoint,
  RemoveFriendRequestLocalApiEndpoint,
  PresenceLocalApiEndpoint,
  SettingsLocalApiEndpoint,
  FriendRequestsLocalApiEndpoint,
  LocalSwaggerDocsLocalApiEndpoint,
  PartyChatInfoLocalApiEndpoint,
  PreGameChatInfoLocalApiEndpoint,
  CurrentGameChatInfoLocalApiEndpoint,
  AllChatInfoLocalApiEndpoint,
  ChatParticipantsLocalApiEndpoint,
  SendChatLocalApiEndpoint,
  ChatHistoryLocalApiEndpoint,
]);

export interface LocalApiEndpoints
  extends LocalHelpLocalApiEndpoint,
    SessionsLocalApiEndpoint,
    RsoUserInfoLocalApiEndpoint,
    ClientRegionLocalApiEndpoint,
    AccountAliasLocalApiEndpoint,
    EntitlementsTokenLocalApiEndpoint,
    ChatSessionLocalApiEndpoint,
    FriendsLocalApiEndpoint,
    SendFriendRequestLocalApiEndpoint,
    RemoveFriendRequestLocalApiEndpoint,
    PresenceLocalApiEndpoint,
    SettingsLocalApiEndpoint,
    FriendRequestsLocalApiEndpoint,
    LocalSwaggerDocsLocalApiEndpoint,
    PartyChatInfoLocalApiEndpoint,
    PreGameChatInfoLocalApiEndpoint,
    CurrentGameChatInfoLocalApiEndpoint,
    AllChatInfoLocalApiEndpoint,
    ChatParticipantsLocalApiEndpoint,
    SendChatLocalApiEndpoint,
    ChatHistoryLocalApiEndpoint {}
