/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios, { type AxiosResponse } from "axios";
import { type AxiosRequestConfig } from "axios";
import { presenceEndpoint } from "valorant-api-types";
import { parseResponseDataFor } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { type LocalApiClient } from "~/clients/local-api";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";

export interface PresenceRequestConfig
  extends AxiosRequestConfig,
    CustomAxiosRequestConfig {}

export type PresenceRawResponse = z.input<
  (typeof presenceEndpoint.responses)["200"]
>;

export type PresenceResponse = z.output<
  (typeof presenceEndpoint.responses)["200"]
>;

export class PresenceLocalApiEndpoint {
  /**
   * @description Get a list of online friends and their activity
   *   If the player is playing Valorant, `private` is a base64-encoded JSON string that contains useful information such as party and in-progress game score.
   */
  getPresence<T = PresenceRawResponse>(
    this: LocalApiClient,
    config: PresenceRequestConfig & { parseResponseData: false },
  ): Promise<AxiosResponse<T>>;
  getPresence<T = PresenceResponse>(
    this: LocalApiClient,
    config?: PresenceRequestConfig,
  ): Promise<AxiosResponse<T>>;
  getPresence<T = PresenceResponse>(
    this: LocalApiClient,
    config: PresenceRequestConfig = {},
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "GET",
      url: presenceEndpoint.suffix,
      ...config,
      transformRequest: [
        parseResponseDataFor(presenceEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                presenceEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
