/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios, { type AxiosResponse } from "axios";
import { removeFriendRequestEndpoint } from "@tqman/valorant-api-types";
import { parseResponseDataFor } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { AxiosRequestConfigWithData } from "~/utils/lib/axios";
import { type LocalApiClient } from "~/clients/local-api";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";

type RemoveFriendRequestBodyData = z.infer<
  typeof removeFriendRequestEndpoint.body
>;

export interface RemoveFriendRequestRequestConfig
  extends AxiosRequestConfigWithData<RemoveFriendRequestBodyData>,
    CustomAxiosRequestConfig {}

export type RemoveFriendRequestResponse = z.input<
  (typeof removeFriendRequestEndpoint.responses)["204"]
>;

export type RemoveFriendRequestParsedResponse = z.output<
  (typeof removeFriendRequestEndpoint.responses)["204"]
>;

export class RemoveFriendRequestLocalApiEndpoint {
  /**
   * @description Removes an outgoing friend request
   */
  deleteRemoveFriendRequest<T = RemoveFriendRequestParsedResponse>(
    this: LocalApiClient,
    config: RemoveFriendRequestRequestConfig & { parseResponseData: true },
  ): Promise<AxiosResponse<T>>;
  deleteRemoveFriendRequest<T = RemoveFriendRequestResponse>(
    this: LocalApiClient,
    config: RemoveFriendRequestRequestConfig,
  ): Promise<AxiosResponse<T>>;
  deleteRemoveFriendRequest<T = RemoveFriendRequestResponse>(
    this: LocalApiClient,
    config: RemoveFriendRequestRequestConfig,
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "DELETE",
      url: removeFriendRequestEndpoint.suffix,
      ...config,
      transformRequest: [
        parseResponseDataFor(removeFriendRequestEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                removeFriendRequestEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
