/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios, { type AxiosResponse } from "axios";
import { type AxiosRequestConfig } from "axios";
import { rsoUserInfoEndpoint } from "valorant-api-types";
import { parseResponseDataFor } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { type LocalApiClient } from "~/clients/local-api";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";

export interface RsoUserInfoRequestConfig
  extends AxiosRequestConfig,
    CustomAxiosRequestConfig {}

export type RsoUserInfoResponse = z.input<
  (typeof rsoUserInfoEndpoint.responses)["200"]
>;

export type RsoUserInfoParsedResponse = z.output<
  (typeof rsoUserInfoEndpoint.responses)["200"]
>;

export class RsoUserInfoLocalApiEndpoint {
  /**
   * @description Get RSO user info
   */
  getrsoUserInfo<T = RsoUserInfoParsedResponse>(
    this: LocalApiClient,
    config: RsoUserInfoRequestConfig & { parseResponseData: true },
  ): Promise<AxiosResponse<T>>;
  getrsoUserInfo<T = RsoUserInfoResponse>(
    this: LocalApiClient,
    config?: RsoUserInfoRequestConfig,
  ): Promise<AxiosResponse<T>>;
  getrsoUserInfo<T = RsoUserInfoResponse>(
    this: LocalApiClient,
    config: RsoUserInfoRequestConfig = {},
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "GET",
      url: rsoUserInfoEndpoint.suffix,
      ...config,
      transformRequest: [
        parseResponseDataFor(rsoUserInfoEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                rsoUserInfoEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
