/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { FetchContentRemoteApiEndpoint } from "./shared/fetch-content";
import { AccountXpRemoteApiEndpoint } from "./pd/account-xp";
import { PlayerLoadoutRemoteApiEndpoint } from "./pd/player-loadout";
import { SetPlayerLoadoutRemoteApiEndpoint } from "./pd/set-player-loadout";
import { PlayerMmrRemoteApiEndpoint } from "./pd/player-mmr";
import { MatchHistoryRemoteApiEndpoint } from "./pd/match-history";
import { MatchDetailsRemoteApiEndpoint } from "./pd/match-details";
import { CompetitiveUpdatesRemoteApiEndpoint } from "./pd/competitive-updates";
import { LeaderboardRemoteApiEndpoint } from "./pd/leaderboard";
import { PenaltiesRemoteApiEndpoint } from "./pd/penalties";
import { ConfigRemoteApiEndpoint } from "./pd/config";
import { NameServiceRemoteApiEndpoint } from "./pd/name-service";
import { PartyRemoteApiEndpoint } from "./glz/party";
import { PartyPlayerRemoteApiEndpoint } from "./glz/party-player";
import { PartyRemovePlayerRemoteApiEndpoint } from "./glz/party-remove-player";
import { PartySetMemberReadyRemoteApiEndpoint } from "./glz/party-set-member-ready";
import { RefreshCompetitiveTierRemoteApiEndpoint } from "./glz/refresh-competitive-tier";
import { RefreshPlayerIdentityRemoteApiEndpoint } from "./glz/refresh-player-identity";
import { RefreshPingsRemoteApiEndpoint } from "./glz/refresh-pings";
import { ChangeQueueRemoteApiEndpoint } from "./glz/change-queue";
import { StartCustomGameRemoteApiEndpoint } from "./glz/start-custom-game";
import { EnterMatchmakingQueueRemoteApiEndpoint } from "./glz/enter-matchmaking-queue";
import { LeaveMatchmakingQueueRemoteApiEndpoint } from "./glz/leave-matchmaking-queue";
import { SetPartyAccessibilityRemoteApiEndpoint } from "./glz/set-party-accessibility";
import { SetCustomGameSettingsRemoteApiEndpoint } from "./glz/set-custom-game-settings";
import { PartyInviteRemoteApiEndpoint } from "./glz/party-invite";
import { PartyRequestRemoteApiEndpoint } from "./glz/party-request";
import { PartyDeclineRemoteApiEndpoint } from "./glz/party-decline";
import { CustomGameConfigsRemoteApiEndpoint } from "./glz/custom-game-configs";
import { PartyChatTokenRemoteApiEndpoint } from "./glz/party-chat-token";
import { PartyVoiceTokenRemoteApiEndpoint } from "./glz/party-voice-token";
import { PricesRemoteApiEndpoint } from "./pd/prices";
import { StorefrontRemoteApiEndpoint } from "./pd/storefront";
import { WalletRemoteApiEndpoint } from "./pd/wallet";
import { OwnedItemsRemoteApiEndpoint } from "./pd/owned-items";
import { PreGamePlayerRemoteApiEndpoint } from "./glz/pre-game-player";
import { PreGameMatchRemoteApiEndpoint } from "./glz/pre-game-match";
import { PreGameLoadoutsRemoteApiEndpoint } from "./glz/pre-game-loadouts";
import { SelectCharacterRemoteApiEndpoint } from "./glz/select-character";
import { LockCharacterRemoteApiEndpoint } from "./glz/lock-character";
import { PreGameQuitRemoteApiEndpoint } from "./glz/pre-game-quit";
import { CurrentGamePlayerRemoteApiEndpoint } from "./glz/current-game-player";
import { CurrentGameMatchRemoteApiEndpoint } from "./glz/current-game-match";
import { CurrentGameLoadoutsRemoteApiEndpoint } from "./glz/current-game-loadouts";
import { ItemUpgradesRemoteApiEndpoint } from "./pd/item-upgrades";
import { ContractsRemoteApiEndpoint } from "./pd/contracts";
import { ActivateContractRemoteApiEndpoint } from "./pd/activate-contract";

import { applyMixins } from "~/utils/classes";

export class RemoteApiEndpoints {}

applyMixins(RemoteApiEndpoints, [
  FetchContentRemoteApiEndpoint,
  AccountXpRemoteApiEndpoint,
  PlayerLoadoutRemoteApiEndpoint,
  SetPlayerLoadoutRemoteApiEndpoint,
  PlayerMmrRemoteApiEndpoint,
  MatchHistoryRemoteApiEndpoint,
  MatchDetailsRemoteApiEndpoint,
  CompetitiveUpdatesRemoteApiEndpoint,
  LeaderboardRemoteApiEndpoint,
  PenaltiesRemoteApiEndpoint,
  ConfigRemoteApiEndpoint,
  NameServiceRemoteApiEndpoint,
  PartyRemoteApiEndpoint,
  PartyPlayerRemoteApiEndpoint,
  PartyRemovePlayerRemoteApiEndpoint,
  PartySetMemberReadyRemoteApiEndpoint,
  RefreshCompetitiveTierRemoteApiEndpoint,
  RefreshPlayerIdentityRemoteApiEndpoint,
  RefreshPingsRemoteApiEndpoint,
  ChangeQueueRemoteApiEndpoint,
  StartCustomGameRemoteApiEndpoint,
  EnterMatchmakingQueueRemoteApiEndpoint,
  LeaveMatchmakingQueueRemoteApiEndpoint,
  SetPartyAccessibilityRemoteApiEndpoint,
  SetCustomGameSettingsRemoteApiEndpoint,
  PartyInviteRemoteApiEndpoint,
  PartyRequestRemoteApiEndpoint,
  PartyDeclineRemoteApiEndpoint,
  CustomGameConfigsRemoteApiEndpoint,
  PartyChatTokenRemoteApiEndpoint,
  PartyVoiceTokenRemoteApiEndpoint,
  PricesRemoteApiEndpoint,
  StorefrontRemoteApiEndpoint,
  WalletRemoteApiEndpoint,
  OwnedItemsRemoteApiEndpoint,
  PreGamePlayerRemoteApiEndpoint,
  PreGameMatchRemoteApiEndpoint,
  PreGameLoadoutsRemoteApiEndpoint,
  SelectCharacterRemoteApiEndpoint,
  LockCharacterRemoteApiEndpoint,
  PreGameQuitRemoteApiEndpoint,
  CurrentGamePlayerRemoteApiEndpoint,
  CurrentGameMatchRemoteApiEndpoint,
  CurrentGameLoadoutsRemoteApiEndpoint,
  ItemUpgradesRemoteApiEndpoint,
  ContractsRemoteApiEndpoint,
  ActivateContractRemoteApiEndpoint,
]);

export interface RemoteApiEndpoints
  extends FetchContentRemoteApiEndpoint,
    AccountXpRemoteApiEndpoint,
    PlayerLoadoutRemoteApiEndpoint,
    SetPlayerLoadoutRemoteApiEndpoint,
    PlayerMmrRemoteApiEndpoint,
    MatchHistoryRemoteApiEndpoint,
    MatchDetailsRemoteApiEndpoint,
    CompetitiveUpdatesRemoteApiEndpoint,
    LeaderboardRemoteApiEndpoint,
    PenaltiesRemoteApiEndpoint,
    ConfigRemoteApiEndpoint,
    NameServiceRemoteApiEndpoint,
    PartyRemoteApiEndpoint,
    PartyPlayerRemoteApiEndpoint,
    PartyRemovePlayerRemoteApiEndpoint,
    PartySetMemberReadyRemoteApiEndpoint,
    RefreshCompetitiveTierRemoteApiEndpoint,
    RefreshPlayerIdentityRemoteApiEndpoint,
    RefreshPingsRemoteApiEndpoint,
    ChangeQueueRemoteApiEndpoint,
    StartCustomGameRemoteApiEndpoint,
    EnterMatchmakingQueueRemoteApiEndpoint,
    LeaveMatchmakingQueueRemoteApiEndpoint,
    SetPartyAccessibilityRemoteApiEndpoint,
    SetCustomGameSettingsRemoteApiEndpoint,
    PartyInviteRemoteApiEndpoint,
    PartyRequestRemoteApiEndpoint,
    PartyDeclineRemoteApiEndpoint,
    CustomGameConfigsRemoteApiEndpoint,
    PartyChatTokenRemoteApiEndpoint,
    PartyVoiceTokenRemoteApiEndpoint,
    PricesRemoteApiEndpoint,
    StorefrontRemoteApiEndpoint,
    WalletRemoteApiEndpoint,
    OwnedItemsRemoteApiEndpoint,
    PreGamePlayerRemoteApiEndpoint,
    PreGameMatchRemoteApiEndpoint,
    PreGameLoadoutsRemoteApiEndpoint,
    SelectCharacterRemoteApiEndpoint,
    LockCharacterRemoteApiEndpoint,
    PreGameQuitRemoteApiEndpoint,
    CurrentGamePlayerRemoteApiEndpoint,
    CurrentGameMatchRemoteApiEndpoint,
    CurrentGameLoadoutsRemoteApiEndpoint,
    ItemUpgradesRemoteApiEndpoint,
    ContractsRemoteApiEndpoint,
    ActivateContractRemoteApiEndpoint {}
