/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios from "axios";
import { type AxiosRequestConfig } from "axios";
import { accountAliasEndpoint } from "valorant-api-types";
import { parseResponseDataFor } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { type LocalApiClient } from "~/clients/local";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";

export interface AccountAliasRequestConfig
  extends AxiosRequestConfig,
    CustomAxiosRequestConfig {}

export type AccountAliasResponse = z.infer<
  (typeof accountAliasEndpoint.responses)["200"]
>;

export class AccountAliasLocalApiEndpoint {
  /**
   * @description Gets the player username and tagline
   */
  getAccountAlias<T = AccountAliasResponse>(
    this: LocalApiClient,
    config: AccountAliasRequestConfig = {},
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "GET",
      url: accountAliasEndpoint.suffix,
      ...config,
      transformRequest: [
        parseResponseDataFor(accountAliasEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                accountAliasEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
