/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios from "axios";
import { type AxiosRequestConfig } from "axios";
import { entitlementsTokenEndpoint } from "valorant-api-types";
import { parseResponseDataFor } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { type LocalApiClient } from "~/clients/local";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";

export interface EntitlementsTokenRequestConfig
  extends AxiosRequestConfig,
    CustomAxiosRequestConfig {}

export type EntitlementsTokenResponse = z.infer<
  (typeof entitlementsTokenEndpoint.responses)["200"]
>;

export class EntitlementsTokenLocalApiEndpoint {
  /**
   * @description Gets both the token and entitlement for API usage
   * `accessToken` is used as the token and `token` is used as the entitlement.
   */
  getEntitlementsToken<T = EntitlementsTokenResponse>(
    this: LocalApiClient,
    config: EntitlementsTokenRequestConfig = {},
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "GET",
      url: entitlementsTokenEndpoint.suffix,
      ...config,
      transformRequest: [
        parseResponseDataFor(entitlementsTokenEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                entitlementsTokenEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
