/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios from "axios";
import { type AxiosRequestConfig } from "axios";
import { settingsEndpoint } from "valorant-api-types";
import { parseResponseDataFor } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { type LocalApiClient } from "~/clients/local";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";

export interface SettingsRequestConfig
  extends AxiosRequestConfig,
    CustomAxiosRequestConfig {}

export type SettingsResponse = z.infer<
  (typeof settingsEndpoint.responses)["200"]
>;

export class SettingsLocalApiEndpoint {
  /**
   * @description Get a list of client settings
   */
  getSettings<T = SettingsResponse>(
    this: LocalApiClient,
    config: SettingsRequestConfig = {},
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "GET",
      url: settingsEndpoint.suffix,
      ...config,
      transformRequest: [
        parseResponseDataFor(settingsEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                settingsEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
