/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import { authRequestEndpoint } from "valorant-api-types";
import { type AuthApiClient } from "~/clients/auth-api";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";
import { AxiosRequestConfigWithData } from "~/utils/lib/axios";

type AuthRequestBodyData = z.infer<typeof authRequestEndpoint.body>;

export interface AuthRequestRequestConfig
  extends AxiosRequestConfigWithData<AuthRequestBodyData>,
    CustomAxiosRequestConfig {}

export class AuthRequestAuthApiEndpoint {
  /**
   * @description Perform authorization request to get token
   * Requires cookies from the [POST Auth Cookies] stage. The token can be found in the `uri` property.
   */
  putAuthRequest<T = any>(
    this: AuthApiClient,
    config: AuthRequestRequestConfig,
  ) {
    return this.axiosInstance<T>({
      method: "PUT",
      url: authRequestEndpoint.suffix,
      headers: Object.fromEntries(authRequestEndpoint.headers),
      ...config,
    });
  }
}
