/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { AuthCookiesAuthApiEndpoint } from "./auth-cookies";
import { AuthRequestAuthApiEndpoint } from "./auth-request";
import { MultiFactorAuthenticationAuthApiEndpoint } from "./multi-factor-authentication";
import { CookieReauthAuthApiEndpoint } from "./cookie-reauth";
import { EntitlementAuthApiEndpoint } from "./entitlement";
import { PlayerInfoAuthApiEndpoint } from "./player-info";

import { applyMixins } from "~/utils/classes";

export class AuthApiEndpoints {}

applyMixins(AuthApiEndpoints, [
  AuthCookiesAuthApiEndpoint,
  AuthRequestAuthApiEndpoint,
  MultiFactorAuthenticationAuthApiEndpoint,
  CookieReauthAuthApiEndpoint,
  EntitlementAuthApiEndpoint,
  PlayerInfoAuthApiEndpoint,
]);

export interface AuthApiEndpoints
  extends AuthCookiesAuthApiEndpoint,
    AuthRequestAuthApiEndpoint,
    MultiFactorAuthenticationAuthApiEndpoint,
    CookieReauthAuthApiEndpoint,
    EntitlementAuthApiEndpoint,
    PlayerInfoAuthApiEndpoint {}
