/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import { multiFactorAuthenticationEndpoint } from "valorant-api-types";
import { type AuthApiClient } from "~/clients/auth-api";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";
import { AxiosRequestConfigWithData } from "~/utils/lib/axios";

type MultiFactorAuthenticationBodyData = z.infer<
  typeof multiFactorAuthenticationEndpoint.body
>;

export interface MultiFactorAuthenticationRequestConfig
  extends AxiosRequestConfigWithData<MultiFactorAuthenticationBodyData>,
    CustomAxiosRequestConfig {}

export class MultiFactorAuthenticationAuthApiEndpoint {
  /**
   * @description Submits a multi-factor authentication code for login
   */
  putMultiFactorAuthentication<T = any>(
    this: AuthApiClient,
    config: MultiFactorAuthenticationRequestConfig,
  ) {
    return this.axiosInstance<T>({
      method: "PUT",
      url: multiFactorAuthenticationEndpoint.suffix,
      headers: Object.fromEntries(multiFactorAuthenticationEndpoint.headers),
      ...config,
    });
  }
}
