/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import { type AxiosRequestConfig } from "axios";
import { playerInfoEndpoint } from "@tqman/valorant-api-types";
import { type AuthApiClient } from "~/clients/auth-api";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";

export interface PlayerInfoRequestConfig
  extends AxiosRequestConfig,
    CustomAxiosRequestConfig {}

export type PlayerInfoResponse = z.infer<
  (typeof playerInfoEndpoint.responses)["200"]
>;

export class PlayerInfoAuthApiEndpoint {
  /**
   * @description Get the PUUID and other info from a token
   */
  getPlayerInfo<T = PlayerInfoResponse>(
    this: AuthApiClient,
    config: PlayerInfoRequestConfig = {},
  ) {
    return this.axiosInstance<T>({
      method: "GET",
      url: playerInfoEndpoint.suffix,

      ...config,
    });
  }
}
