/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios from "axios";
import { contractsEndpoint } from "valorant-api-types";
import { parseResponseDataFor, buildSuffix } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { AxiosRequestConfigWithData } from "~/utils/lib/axios";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";
import { type RemoteApiClient } from "~/clients/remote";

type ContractsSuffixData = { puuid: string };

export interface ContractsRequestConfig
  extends AxiosRequestConfigWithData<ContractsSuffixData>,
    CustomAxiosRequestConfig {}

export type ContractsResponse = z.infer<
  (typeof contractsEndpoint.responses)["200"]
>;

export class ContractsRemoteApiEndpoint {
  /**
   * @description Get contract details including agents, battlepass, missions, and recent games
   */
  getContracts<T = ContractsResponse>(
    this: RemoteApiClient,
    config: ContractsRequestConfig,
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "GET",
      baseURL: this.getServerUrl(contractsEndpoint.type),
      url: buildSuffix(contractsEndpoint.suffix, config.data),
      ...config,
      transformRequest: [
        parseResponseDataFor(contractsEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                contractsEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
