/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios from "axios";
import { leaderboardEndpoint } from "valorant-api-types";
import { parseResponseDataFor, buildSuffix } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { AxiosRequestConfigWithData } from "~/utils/lib/axios";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";
import { type RemoteApiClient } from "~/clients/remote";

type LeaderboardSuffixData = { seasonId: string };

export interface LeaderboardRequestConfig
  extends AxiosRequestConfigWithData<LeaderboardSuffixData>,
    CustomAxiosRequestConfig {}

export type LeaderboardResponse = z.infer<
  (typeof leaderboardEndpoint.responses)["200"]
>;

export class LeaderboardRemoteApiEndpoint {
  /**
   * @description Get the leaderboard for a given season
   */
  getLeaderboard<T = LeaderboardResponse>(
    this: RemoteApiClient,
    config: LeaderboardRequestConfig,
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "GET",
      baseURL: this.getServerUrl(leaderboardEndpoint.type),
      url: buildSuffix(leaderboardEndpoint.suffix, config.data),
      ...config,
      transformRequest: [
        parseResponseDataFor(leaderboardEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                leaderboardEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
