/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios from "axios";
import { playerMMREndpoint } from "valorant-api-types";
import { parseResponseDataFor, buildSuffix } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { AxiosRequestConfigWithData } from "~/utils/lib/axios";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";
import { type RemoteApiClient } from "~/clients/remote";

type PlayerMmrSuffixData = { puuid: string };

export interface PlayerMmrRequestConfig
  extends AxiosRequestConfigWithData<PlayerMmrSuffixData>,
    CustomAxiosRequestConfig {}

export type PlayerMmrResponse = z.infer<
  (typeof playerMMREndpoint.responses)["200"]
>;

export class PlayerMmrRemoteApiEndpoint {
  /**
   * @description Get a player's MMR and history
   */
  getPlayerMmr<T = PlayerMmrResponse>(
    this: RemoteApiClient,
    config: PlayerMmrRequestConfig,
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "GET",
      baseURL: this.getServerUrl(playerMMREndpoint.type),
      url: buildSuffix(playerMMREndpoint.suffix, config.data),
      ...config,
      transformRequest: [
        parseResponseDataFor(playerMMREndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                playerMMREndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
