import { writeFile } from "fs/promises";

import {
  createValorantApiClient,
  provideLockFile,
  useProviders,
} from "~/index.js";
import { javascript } from "~/utils/template";

const vapic = await createValorantApiClient({
  local: useProviders([provideLockFile()]),
}).catch(e => {
  console.log("Make sure Valorant is running!");
  console.error("Error:", e.message);
  process.exit(1);
});

const { data: help } = await vapic.local.api.getLocalHelp();

const header = "/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */\n\n";
const template =
  header +
  javascript`export const EVENTS = ${JSON.stringify(
    Object.keys(help.events),
    null,
    2
  )} as const
`;

writeFile("src/ws-client/events.autogen.ts", template, { encoding: "utf8" })
  .then(() => console.log("Written to assets/help.json"))
  .catch(e => {
    console.log("Error writing to file assets/help.json");
    console.error("Error:", e.message);
  });
