/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios from "axios";
import { partyRequestEndpoint } from "valorant-api-types";
import { parseResponseDataFor, buildSuffix } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { AxiosRequestConfigWithData } from "~/utils/lib/axios";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";
import { type RemoteApiClient } from "~/clients/remote";

type PartyRequestSuffixData = { partyId: string };

export interface PartyRequestRequestConfig
  extends AxiosRequestConfigWithData<PartyRequestSuffixData>,
    CustomAxiosRequestConfig {}

export type PartyRequestResponse = z.infer<
  (typeof partyRequestEndpoint.responses)["200"]
>;

export class PartyRequestRemoteApiEndpoint {
  /**
   * @description Requests to join the specified party ID
   */
  postPartyRequest<T = PartyRequestResponse>(
    this: RemoteApiClient,
    config: PartyRequestRequestConfig,
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "POST",
      baseURL: this.getServerUrl(partyRequestEndpoint.type),
      url: buildSuffix(partyRequestEndpoint.suffix, config.data),
      ...config,
      transformRequest: [
        parseResponseDataFor(partyRequestEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                partyRequestEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
