/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios from "axios";
import { changeQueueEndpoint } from "valorant-api-types";
import { parseResponseDataFor, buildSuffix } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { AxiosRequestConfigWithData } from "~/utils/lib/axios";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";
import { type RemoteApiClient } from "~/clients/remote-api";

type ChangeQueueBodyData = z.infer<typeof changeQueueEndpoint.body>;

type ChangeQueueSuffixData = { partyId: string };

export interface ChangeQueueRequestConfig
  extends AxiosRequestConfigWithData<
      ChangeQueueBodyData & ChangeQueueSuffixData
    >,
    CustomAxiosRequestConfig {}

export type ChangeQueueResponse = z.infer<
  (typeof changeQueueEndpoint.responses)["200"]
>;

export class ChangeQueueRemoteApiEndpoint {
  /**
   * @description Change the queue for the party
   */
  postChangeQueue<T = ChangeQueueResponse>(
    this: RemoteApiClient,
    config: ChangeQueueRequestConfig,
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "POST",
      baseURL: this.getServerUrl(changeQueueEndpoint.type),
      url: buildSuffix(changeQueueEndpoint.suffix, config.data),
      ...config,
      transformRequest: [
        parseResponseDataFor(changeQueueEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                changeQueueEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
