/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios, { type AxiosResponse } from "axios";
import { currentGameQuitEndpoint } from "@tqman/valorant-api-types";
import { parseResponseDataFor, buildSuffix } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { AxiosRequestConfigWithData } from "~/utils/lib/axios";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";
import { type RemoteApiClient } from "~/clients/remote-api";

type CurrentGameQuitSuffixData = { puuid: string; currentGameMatchId: string };

export interface CurrentGameQuitRequestConfig
  extends AxiosRequestConfigWithData<CurrentGameQuitSuffixData>,
    CustomAxiosRequestConfig {}

export type CurrentGameQuitResponse = z.input<
  (typeof currentGameQuitEndpoint.responses)["204"]
>;

export type CurrentGameQuitParsedResponse = z.output<
  (typeof currentGameQuitEndpoint.responses)["204"]
>;

export class CurrentGameQuitRemoteApiEndpoint {
  /**
   * @description Quits the current game
   */
  postCurrentGameQuit<T = CurrentGameQuitParsedResponse>(
    this: RemoteApiClient,
    config: CurrentGameQuitRequestConfig & { parseResponseData: true },
  ): Promise<AxiosResponse<T>>;
  postCurrentGameQuit<T = CurrentGameQuitResponse>(
    this: RemoteApiClient,
    config?: CurrentGameQuitRequestConfig,
  ): Promise<AxiosResponse<T>>;
  postCurrentGameQuit<T = CurrentGameQuitResponse>(
    this: RemoteApiClient,
    config: CurrentGameQuitRequestConfig,
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "POST",
      baseURL: this.getServerUrl(currentGameQuitEndpoint.type),
      url: buildSuffix(currentGameQuitEndpoint.suffix, config.data),
      ...config,
      transformRequest: [
        parseResponseDataFor(currentGameQuitEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                currentGameQuitEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
