/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios from "axios";
import { enterMatchmakingQueueEndpoint } from "valorant-api-types";
import { parseResponseDataFor, buildSuffix } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { AxiosRequestConfigWithData } from "~/utils/lib/axios";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";
import { type RemoteApiClient } from "~/clients/remote-api";

type EnterMatchmakingQueueSuffixData = { partyId: string };

export interface EnterMatchmakingQueueRequestConfig
  extends AxiosRequestConfigWithData<EnterMatchmakingQueueSuffixData>,
    CustomAxiosRequestConfig {}

export type EnterMatchmakingQueueResponse = z.infer<
  (typeof enterMatchmakingQueueEndpoint.responses)["200"]
>;

export class EnterMatchmakingQueueRemoteApiEndpoint {
  /**
   * @description Enter the matchmaking queue for the party
   */
  postEnterMatchmakingQueue<T = EnterMatchmakingQueueResponse>(
    this: RemoteApiClient,
    config: EnterMatchmakingQueueRequestConfig,
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "POST",
      baseURL: this.getServerUrl(enterMatchmakingQueueEndpoint.type),
      url: buildSuffix(enterMatchmakingQueueEndpoint.suffix, config.data),
      ...config,
      transformRequest: [
        parseResponseDataFor(enterMatchmakingQueueEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                enterMatchmakingQueueEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
