/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios, { type AxiosResponse } from "axios";
import { leaveMatchmakingQueueEndpoint } from "@tqman/valorant-api-types";
import { parseResponseDataFor, buildSuffix } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { AxiosRequestConfigWithData } from "~/utils/lib/axios";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";
import { type RemoteApiClient } from "~/clients/remote-api";

type LeaveMatchmakingQueueSuffixData = { partyId: string };

export interface LeaveMatchmakingQueueRequestConfig
  extends AxiosRequestConfigWithData<LeaveMatchmakingQueueSuffixData>,
    CustomAxiosRequestConfig {}

export type LeaveMatchmakingQueueResponse = z.input<
  (typeof leaveMatchmakingQueueEndpoint.responses)["200"]
>;

export type LeaveMatchmakingQueueParsedResponse = z.output<
  (typeof leaveMatchmakingQueueEndpoint.responses)["200"]
>;

export class LeaveMatchmakingQueueRemoteApiEndpoint {
  /**
   * @description Leave the matchmaking queue for the party
   */
  postLeaveMatchmakingQueue<T = LeaveMatchmakingQueueParsedResponse>(
    this: RemoteApiClient,
    config: LeaveMatchmakingQueueRequestConfig & { parseResponseData: true },
  ): Promise<AxiosResponse<T>>;
  postLeaveMatchmakingQueue<T = LeaveMatchmakingQueueResponse>(
    this: RemoteApiClient,
    config?: LeaveMatchmakingQueueRequestConfig,
  ): Promise<AxiosResponse<T>>;
  postLeaveMatchmakingQueue<T = LeaveMatchmakingQueueResponse>(
    this: RemoteApiClient,
    config: LeaveMatchmakingQueueRequestConfig,
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "POST",
      baseURL: this.getServerUrl(leaveMatchmakingQueueEndpoint.type),
      url: buildSuffix(leaveMatchmakingQueueEndpoint.suffix, config.data),
      ...config,
      transformRequest: [
        parseResponseDataFor(leaveMatchmakingQueueEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                leaveMatchmakingQueueEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
