/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios, { type AxiosResponse } from "axios";
import { partyInviteEndpoint } from "valorant-api-types";
import { parseResponseDataFor, buildSuffix } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { AxiosRequestConfigWithData } from "~/utils/lib/axios";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";
import { type RemoteApiClient } from "~/clients/remote-api";

type PartyInviteSuffixData = { partyId: string; name: string; tagline: string };

export interface PartyInviteRequestConfig
  extends AxiosRequestConfigWithData<PartyInviteSuffixData>,
    CustomAxiosRequestConfig {}

export type PartyInviteRawResponse = z.input<
  (typeof partyInviteEndpoint.responses)["200"]
>;

export type PartyInviteResponse = z.output<
  (typeof partyInviteEndpoint.responses)["200"]
>;

export class PartyInviteRemoteApiEndpoint {
  /**
   * @description Invite a player to the party by name and tagline
   */
  postPartyInvite<T = PartyInviteRawResponse>(
    this: RemoteApiClient,
    config: PartyInviteRequestConfig & { parseResponseData: false },
  ): Promise<AxiosResponse<T>>;
  postPartyInvite<T = PartyInviteResponse>(
    this: RemoteApiClient,
    config?: PartyInviteRequestConfig,
  ): Promise<AxiosResponse<T>>;
  postPartyInvite<T = PartyInviteResponse>(
    this: RemoteApiClient,
    config: PartyInviteRequestConfig,
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "POST",
      baseURL: this.getServerUrl(partyInviteEndpoint.type),
      url: buildSuffix(partyInviteEndpoint.suffix, config.data),
      ...config,
      transformRequest: [
        parseResponseDataFor(partyInviteEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                partyInviteEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
