/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios from "axios";
import { partyDeclineEndpoint } from "valorant-api-types";
import { parseResponseDataFor, buildSuffix } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { AxiosRequestConfigWithData } from "~/utils/lib/axios";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";
import { type RemoteApiClient } from "~/clients/remote-api";

type PartyDeclineSuffixData = { partyId: string; requestId: string };

export interface PartyDeclineRequestConfig
  extends AxiosRequestConfigWithData<PartyDeclineSuffixData>,
    CustomAxiosRequestConfig {}

export type PartyDeclineResponse = z.infer<
  (typeof partyDeclineEndpoint.responses)["200"]
>;

export class PartyDeclineRemoteApiEndpoint {
  /**
   * @description Decline a party invite request
   */
  postPartyDecline<T = PartyDeclineResponse>(
    this: RemoteApiClient,
    config: PartyDeclineRequestConfig,
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "POST",
      baseURL: this.getServerUrl(partyDeclineEndpoint.type),
      url: buildSuffix(partyDeclineEndpoint.suffix, config.data),
      ...config,
      transformRequest: [
        parseResponseDataFor(partyDeclineEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                partyDeclineEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
