/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios, { type AxiosResponse } from "axios";
import { partyVoiceTokenEndpoint } from "valorant-api-types";
import { parseResponseDataFor, buildSuffix } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { AxiosRequestConfigWithData } from "~/utils/lib/axios";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";
import { type RemoteApiClient } from "~/clients/remote-api";

type PartyVoiceTokenSuffixData = { partyId: string };

export interface PartyVoiceTokenRequestConfig
  extends AxiosRequestConfigWithData<PartyVoiceTokenSuffixData>,
    CustomAxiosRequestConfig {}

export type PartyVoiceTokenResponse = z.input<
  (typeof partyVoiceTokenEndpoint.responses)["200"]
>;

export type PartyVoiceTokenParsedResponse = z.output<
  (typeof partyVoiceTokenEndpoint.responses)["200"]
>;

export class PartyVoiceTokenRemoteApiEndpoint {
  /**
   * @description Get the party voice token
   */
  getPartyVoiceToken<T = PartyVoiceTokenParsedResponse>(
    this: RemoteApiClient,
    config: PartyVoiceTokenRequestConfig & { parseResponseData: true },
  ): Promise<AxiosResponse<T>>;
  getPartyVoiceToken<T = PartyVoiceTokenResponse>(
    this: RemoteApiClient,
    config?: PartyVoiceTokenRequestConfig,
  ): Promise<AxiosResponse<T>>;
  getPartyVoiceToken<T = PartyVoiceTokenResponse>(
    this: RemoteApiClient,
    config: PartyVoiceTokenRequestConfig,
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "GET",
      baseURL: this.getServerUrl(partyVoiceTokenEndpoint.type),
      url: buildSuffix(partyVoiceTokenEndpoint.suffix, config.data),
      ...config,
      transformRequest: [
        parseResponseDataFor(partyVoiceTokenEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                partyVoiceTokenEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
