/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios, { type AxiosResponse } from "axios";
import { partyPlayerEndpoint } from "valorant-api-types";
import { parseResponseDataFor, buildSuffix } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { AxiosRequestConfigWithData } from "~/utils/lib/axios";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";
import { type RemoteApiClient } from "~/clients/remote-api";

type PartyPlayerSuffixData = { puuid: string };

export interface PartyPlayerRequestConfig
  extends AxiosRequestConfigWithData<PartyPlayerSuffixData>,
    CustomAxiosRequestConfig {}

export type PartyPlayerRawResponse = z.input<
  (typeof partyPlayerEndpoint.responses)["200"]
>;

export type PartyPlayerResponse = z.output<
  (typeof partyPlayerEndpoint.responses)["200"]
>;

export class PartyPlayerRemoteApiEndpoint {
  /**
   * @description Get the party information for the given player
   */
  getPartyPlayer<T = PartyPlayerRawResponse>(
    this: RemoteApiClient,
    config: PartyPlayerRequestConfig & { parseResponseData: false },
  ): Promise<AxiosResponse<T>>;
  getPartyPlayer<T = PartyPlayerResponse>(
    this: RemoteApiClient,
    config?: PartyPlayerRequestConfig,
  ): Promise<AxiosResponse<T>>;
  getPartyPlayer<T = PartyPlayerResponse>(
    this: RemoteApiClient,
    config: PartyPlayerRequestConfig,
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "GET",
      baseURL: this.getServerUrl(partyPlayerEndpoint.type),
      url: buildSuffix(partyPlayerEndpoint.suffix, config.data),
      ...config,
      transformRequest: [
        parseResponseDataFor(partyPlayerEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                partyPlayerEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
