/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios, { type AxiosResponse } from "axios";
import { partyChatTokenEndpoint } from "@tqman/valorant-api-types";
import { parseResponseDataFor, buildSuffix } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { AxiosRequestConfigWithData } from "~/utils/lib/axios";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";
import { type RemoteApiClient } from "~/clients/remote-api";

type PartyChatTokenSuffixData = { partyId: string };

export interface PartyChatTokenRequestConfig
  extends AxiosRequestConfigWithData<PartyChatTokenSuffixData>,
    CustomAxiosRequestConfig {}

export type PartyChatTokenResponse = z.input<
  (typeof partyChatTokenEndpoint.responses)["200"]
>;

export type PartyChatTokenParsedResponse = z.output<
  (typeof partyChatTokenEndpoint.responses)["200"]
>;

export class PartyChatTokenRemoteApiEndpoint {
  /**
   * @description Get the party chat token
   */
  getPartyChatToken<T = PartyChatTokenParsedResponse>(
    this: RemoteApiClient,
    config: PartyChatTokenRequestConfig & { parseResponseData: true },
  ): Promise<AxiosResponse<T>>;
  getPartyChatToken<T = PartyChatTokenResponse>(
    this: RemoteApiClient,
    config?: PartyChatTokenRequestConfig,
  ): Promise<AxiosResponse<T>>;
  getPartyChatToken<T = PartyChatTokenResponse>(
    this: RemoteApiClient,
    config: PartyChatTokenRequestConfig,
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "GET",
      baseURL: this.getServerUrl(partyChatTokenEndpoint.type),
      url: buildSuffix(partyChatTokenEndpoint.suffix, config.data),
      ...config,
      transformRequest: [
        parseResponseDataFor(partyChatTokenEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                partyChatTokenEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
