/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios, { type AxiosResponse } from "axios";
import { pregameLoadoutsEndpoint } from "valorant-api-types";
import { parseResponseDataFor, buildSuffix } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { AxiosRequestConfigWithData } from "~/utils/lib/axios";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";
import { type RemoteApiClient } from "~/clients/remote-api";

type PreGameLoadoutsSuffixData = { preGameMatchId: string };

export interface PreGameLoadoutsRequestConfig
  extends AxiosRequestConfigWithData<PreGameLoadoutsSuffixData>,
    CustomAxiosRequestConfig {}

export type PreGameLoadoutsRawResponse = z.input<
  (typeof pregameLoadoutsEndpoint.responses)["200"]
>;

export type PreGameLoadoutsResponse = z.output<
  (typeof pregameLoadoutsEndpoint.responses)["200"]
>;

export class PreGameLoadoutsRemoteApiEndpoint {
  /**
   * @description Get Pre-Game loadout data
   */
  getPreGameLoadouts<T = PreGameLoadoutsRawResponse>(
    this: RemoteApiClient,
    config: PreGameLoadoutsRequestConfig & { parseResponseData: false },
  ): Promise<AxiosResponse<T>>;
  getPreGameLoadouts<T = PreGameLoadoutsResponse>(
    this: RemoteApiClient,
    config?: PreGameLoadoutsRequestConfig,
  ): Promise<AxiosResponse<T>>;
  getPreGameLoadouts<T = PreGameLoadoutsResponse>(
    this: RemoteApiClient,
    config: PreGameLoadoutsRequestConfig,
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "GET",
      baseURL: this.getServerUrl(pregameLoadoutsEndpoint.type),
      url: buildSuffix(pregameLoadoutsEndpoint.suffix, config.data),
      ...config,
      transformRequest: [
        parseResponseDataFor(pregameLoadoutsEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                pregameLoadoutsEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
