/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios, { type AxiosResponse } from "axios";
import { pregameMatchEndpoint } from "valorant-api-types";
import { parseResponseDataFor, buildSuffix } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { AxiosRequestConfigWithData } from "~/utils/lib/axios";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";
import { type RemoteApiClient } from "~/clients/remote-api";

type PreGameMatchSuffixData = { preGameMatchId: string };

export interface PreGameMatchRequestConfig
  extends AxiosRequestConfigWithData<PreGameMatchSuffixData>,
    CustomAxiosRequestConfig {}

export type PreGameMatchRawResponse = z.input<
  (typeof pregameMatchEndpoint.responses)["200"]
>;

export type PreGameMatchResponse = z.output<
  (typeof pregameMatchEndpoint.responses)["200"]
>;

export class PreGameMatchRemoteApiEndpoint {
  /**
   * @description Get Pre-Game match data
   */
  getPreGameMatch<T = PreGameMatchRawResponse>(
    this: RemoteApiClient,
    config: PreGameMatchRequestConfig & { parseResponseData: false },
  ): Promise<AxiosResponse<T>>;
  getPreGameMatch<T = PreGameMatchResponse>(
    this: RemoteApiClient,
    config?: PreGameMatchRequestConfig,
  ): Promise<AxiosResponse<T>>;
  getPreGameMatch<T = PreGameMatchResponse>(
    this: RemoteApiClient,
    config: PreGameMatchRequestConfig,
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "GET",
      baseURL: this.getServerUrl(pregameMatchEndpoint.type),
      url: buildSuffix(pregameMatchEndpoint.suffix, config.data),
      ...config,
      transformRequest: [
        parseResponseDataFor(pregameMatchEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                pregameMatchEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
