/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios from "axios";
import { pregameQuitEndpoint } from "valorant-api-types";
import { parseResponseDataFor, buildSuffix } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { AxiosRequestConfigWithData } from "~/utils/lib/axios";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";
import { type RemoteApiClient } from "~/clients/remote-api";

type PreGameQuitSuffixData = { preGameMatchId: string };

export interface PreGameQuitRequestConfig
  extends AxiosRequestConfigWithData<PreGameQuitSuffixData>,
    CustomAxiosRequestConfig {}

export type PreGameQuitResponse = z.infer<
  (typeof pregameQuitEndpoint.responses)["204"]
>;

export class PreGameQuitRemoteApiEndpoint {
  /**
   * @description Quit the pre-game lobby
   */
  postPreGameQuit<T = PreGameQuitResponse>(
    this: RemoteApiClient,
    config: PreGameQuitRequestConfig,
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "POST",
      baseURL: this.getServerUrl(pregameQuitEndpoint.type),
      url: buildSuffix(pregameQuitEndpoint.suffix, config.data),
      ...config,
      transformRequest: [
        parseResponseDataFor(pregameQuitEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                pregameQuitEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
