/* THIS IS AN AUTOGENERATED FILE - DO NOT EDIT */

import { z } from "zod";
import axios, { type AxiosResponse } from "axios";
import { refreshCompetitiveTierEndpoint } from "@tqman/valorant-api-types";
import { parseResponseDataFor, buildSuffix } from "~/helpers/endpoints";
import { ensureArray } from "~/utils/array";
import { AxiosRequestConfigWithData } from "~/utils/lib/axios";
import { type CustomAxiosRequestConfig } from "~/clients/common/types";
import { type RemoteApiClient } from "~/clients/remote-api";

type RefreshCompetitiveTierSuffixData = { partyId: string; puuid: string };

export interface RefreshCompetitiveTierRequestConfig
  extends AxiosRequestConfigWithData<RefreshCompetitiveTierSuffixData>,
    CustomAxiosRequestConfig {}

export type RefreshCompetitiveTierResponse = z.input<
  (typeof refreshCompetitiveTierEndpoint.responses)["200"]
>;

export type RefreshCompetitiveTierParsedResponse = z.output<
  (typeof refreshCompetitiveTierEndpoint.responses)["200"]
>;

export class RefreshCompetitiveTierRemoteApiEndpoint {
  /**
   * @description Refresh the competitive tier of the specified player
   */
  postRefreshCompetitiveTier<T = RefreshCompetitiveTierParsedResponse>(
    this: RemoteApiClient,
    config: RefreshCompetitiveTierRequestConfig & { parseResponseData: true },
  ): Promise<AxiosResponse<T>>;
  postRefreshCompetitiveTier<T = RefreshCompetitiveTierResponse>(
    this: RemoteApiClient,
    config?: RefreshCompetitiveTierRequestConfig,
  ): Promise<AxiosResponse<T>>;
  postRefreshCompetitiveTier<T = RefreshCompetitiveTierResponse>(
    this: RemoteApiClient,
    config: RefreshCompetitiveTierRequestConfig,
  ) {
    const shouldParseResponse =
      config.parseResponseData ?? this.options.parseResponseData;

    return this.axiosInstance<T>({
      method: "POST",
      baseURL: this.getServerUrl(refreshCompetitiveTierEndpoint.type),
      url: buildSuffix(refreshCompetitiveTierEndpoint.suffix, config.data),
      ...config,
      transformRequest: [
        parseResponseDataFor(refreshCompetitiveTierEndpoint),
        ...ensureArray(axios.defaults.transformRequest),
      ],
      ...(shouldParseResponse
        ? {
            transformResponse: [
              ...ensureArray(axios.defaults.transformResponse),
              parseResponseDataFor(
                refreshCompetitiveTierEndpoint,
                config.customResponseParser,
              ),
            ],
          }
        : {}),
    });
  }
}
